package entity;
// Generated 03-Mar-2021, 7:30:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Accounts generated by hbm2java
 */
public class Accounts  implements java.io.Serializable {


     private Integer acccountId;
     private String email;
     private String password;
     private boolean active;
     private String role;
     private Set<Shopkeeper> shopkeepers = new HashSet<Shopkeeper>(0);
     private Set<Customer> customers = new HashSet<Customer>(0);
     private Set<DeliveryBoy> deliveryBoys = new HashSet<DeliveryBoy>(0);

    public Accounts() {
    }

	
    public Accounts(String email, String password, boolean active, String role) {
        this.email = email;
        this.password = password;
        this.active = active;
        this.role = role;
    }
    public Accounts(String email, String password, boolean active, String role, Set<Shopkeeper> shopkeepers, Set<Customer> customers, Set<DeliveryBoy> deliveryBoys) {
       this.email = email;
       this.password = password;
       this.active = active;
       this.role = role;
       this.shopkeepers = shopkeepers;
       this.customers = customers;
       this.deliveryBoys = deliveryBoys;
    }
   
    public Accounts(String email, String password) {
        this.email = email;
        this.password = password;
    }
    
   
    public Integer getAcccountId() {
        return this.acccountId;
    }
    
    public void setAcccountId(Integer acccountId) {
        this.acccountId = acccountId;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    public Set<Shopkeeper> getShopkeepers() {
        return this.shopkeepers;
    }
    
    public void setShopkeepers(Set<Shopkeeper> shopkeepers) {
        this.shopkeepers = shopkeepers;
    }
    public Set<Customer> getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Set<Customer> customers) {
        this.customers = customers;
    }
    public Set<DeliveryBoy> getDeliveryBoys() {
        return this.deliveryBoys;
    }
    
    public void setDeliveryBoys(Set<DeliveryBoy> deliveryBoys) {
        this.deliveryBoys = deliveryBoys;
    }




}


