package entity;
// Generated 06-Mar-2021, 9:12:15 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private Integer CId;
     private Accounts accounts;
     private String name;
     private String address;
     private long phone;
     private String email;
     private Set<Cart> carts = new HashSet<Cart>(0);
     private Set<Orders> orderses = new HashSet<Orders>(0);

    public Customer() {
    }

	
    public Customer(Accounts accounts, String name, String address, long phone, String email) {
        this.accounts = accounts;
        this.name = name;
        this.address = address;
        this.phone = phone;
        this.email = email;
    }
    public Customer(Accounts accounts, String name, String address, long phone, String email, Set<Cart> carts, Set<Orders> orderses) {
       this.accounts = accounts;
       this.name = name;
       this.address = address;
       this.phone = phone;
       this.email = email;
       this.carts = carts;
       this.orderses = orderses;
    }
   
    public Integer getCId() {
        return this.CId;
    }
    
    public void setCId(Integer CId) {
        this.CId = CId;
    }
    public Accounts getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Accounts accounts) {
        this.accounts = accounts;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public long getPhone() {
        return this.phone;
    }
    
    public void setPhone(long phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set<Cart> getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set<Cart> carts) {
        this.carts = carts;
    }
    public Set<Orders> getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set<Orders> orderses) {
        this.orderses = orderses;
    }




}


