package entity;
// Generated 02-Mar-2021, 6:31:47 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DeliveryBoy generated by hbm2java
 */
public class DeliveryBoy  implements java.io.Serializable {


     private Integer dbId;
     private Accounts accounts;
     private String name;
     private int phone;
     private String email;
     private int salary;
     private Date hireDate;
     private Integer orderTaken;
     private Set<Orders> orderses = new HashSet<Orders>(0);

    public DeliveryBoy() {
    }

	
    public DeliveryBoy(Accounts accounts, String name, int phone, String email, int salary, Date hireDate) {
        this.accounts = accounts;
        this.name = name;
        this.phone = phone;
        this.email = email;
        this.salary = salary;
        this.hireDate = hireDate;
    }
    public DeliveryBoy(Accounts accounts, String name, int phone, String email, int salary, Date hireDate, Integer orderTaken, Set<Orders> orderses) {
       this.accounts = accounts;
       this.name = name;
       this.phone = phone;
       this.email = email;
       this.salary = salary;
       this.hireDate = hireDate;
       this.orderTaken = orderTaken;
       this.orderses = orderses;
    }
   
    public Integer getDbId() {
        return this.dbId;
    }
    
    public void setDbId(Integer dbId) {
        this.dbId = dbId;
    }
    public Accounts getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Accounts accounts) {
        this.accounts = accounts;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getPhone() {
        return this.phone;
    }
    
    public void setPhone(int phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public int getSalary() {
        return this.salary;
    }
    
    public void setSalary(int salary) {
        this.salary = salary;
    }
    public Date getHireDate() {
        return this.hireDate;
    }
    
    public void setHireDate(Date hireDate) {
        this.hireDate = hireDate;
    }
    public Integer getOrderTaken() {
        return this.orderTaken;
    }
    
    public void setOrderTaken(Integer orderTaken) {
        this.orderTaken = orderTaken;
    }
    public Set<Orders> getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set<Orders> orderses) {
        this.orderses = orderses;
    }




}


