package entity;
// Generated 06-Mar-2021, 9:12:15 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DeliveryBoyDetail generated by hbm2java
 */
public class DeliveryBoyDetail  implements java.io.Serializable {


     private Integer id;
     private DeliveryBoy deliveryBoy;
     private Date salaryDate;
     private int salary;

    public DeliveryBoyDetail() {
    }

    public DeliveryBoyDetail(DeliveryBoy deliveryBoy, Date salaryDate, int salary) {
       this.deliveryBoy = deliveryBoy;
       this.salaryDate = salaryDate;
       this.salary = salary;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public DeliveryBoy getDeliveryBoy() {
        return this.deliveryBoy;
    }
    
    public void setDeliveryBoy(DeliveryBoy deliveryBoy) {
        this.deliveryBoy = deliveryBoy;
    }
    public Date getSalaryDate() {
        return this.salaryDate;
    }
    
    public void setSalaryDate(Date salaryDate) {
        this.salaryDate = salaryDate;
    }
    public int getSalary() {
        return this.salary;
    }
    
    public void setSalary(int salary) {
        this.salary = salary;
    }




}


