package entity;
// Generated 03-Mar-2021, 7:30:03 PM by Hibernate Tools 4.3.1



/**
 * OrderDetails generated by hbm2java
 */
public class OrderDetails  implements java.io.Serializable {


     private Integer id;
     private Orders orders;
     private Products products;
     private Shopkeeper shopkeeper;
     private int price;
     private int amount;
     private int quantity;

    public OrderDetails() {
    }

    public OrderDetails(Orders orders, Products products, Shopkeeper shopkeeper, int price, int amount, int quantity) {
       this.orders = orders;
       this.products = products;
       this.shopkeeper = shopkeeper;
       this.price = price;
       this.amount = amount;
       this.quantity = quantity;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public Shopkeeper getShopkeeper() {
        return this.shopkeeper;
    }
    
    public void setShopkeeper(Shopkeeper shopkeeper) {
        this.shopkeeper = shopkeeper;
    }
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }
    public int getAmount() {
        return this.amount;
    }
    
    public void setAmount(int amount) {
        this.amount = amount;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }




}


