package entity;
// Generated 06-Mar-2021, 8:41:49 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Orders generated by hbm2java
 */
public class Orders  implements java.io.Serializable {


     private Integer OId;
     private Customer customer;
     private DeliveryBoy deliveryBoy;
     private int amount;
     private Date orderDate;
     private int status;
     private String address;
     private Set<OrderDetails> orderDetailses = new HashSet<OrderDetails>(0);

    public Orders() {
    }

	
    public Orders(Customer customer, DeliveryBoy deliveryBoy, int amount, Date orderDate, int status, String address) {
        this.customer = customer;
        this.deliveryBoy = deliveryBoy;
        this.amount = amount;
        this.orderDate = orderDate;
        this.status = status;
        this.address = address;
    }
    public Orders(Customer customer, DeliveryBoy deliveryBoy, int amount, Date orderDate, int status, String address, Set<OrderDetails> orderDetailses) {
       this.customer = customer;
       this.deliveryBoy = deliveryBoy;
       this.amount = amount;
       this.orderDate = orderDate;
       this.status = status;
       this.address = address;
       this.orderDetailses = orderDetailses;
    }
   
    public Integer getOId() {
        return this.OId;
    }
    
    public void setOId(Integer OId) {
        this.OId = OId;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public DeliveryBoy getDeliveryBoy() {
        return this.deliveryBoy;
    }
    
    public void setDeliveryBoy(DeliveryBoy deliveryBoy) {
        this.deliveryBoy = deliveryBoy;
    }
    public int getAmount() {
        return this.amount;
    }
    
    public void setAmount(int amount) {
        this.amount = amount;
    }
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Set<OrderDetails> getOrderDetailses() {
        return this.orderDetailses;
    }
    
    public void setOrderDetailses(Set<OrderDetails> orderDetailses) {
        this.orderDetailses = orderDetailses;
    }




}


