package entity;
// Generated 06-Mar-2021, 8:41:49 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
public class Products  implements java.io.Serializable {


     private Integer PId;
     private Shopkeeper shopkeeper;
     private Uom uom;
     private String name;
     private int quantity;
     private int price;
     private byte[] image;
     private Set<OrderDetails> orderDetailses = new HashSet<OrderDetails>(0);
     private Set<Cart> carts = new HashSet<Cart>(0);

    public Products() {
    }

	
    public Products(Shopkeeper shopkeeper, Uom uom, String name, int quantity, int price, byte[] image) {
        this.shopkeeper = shopkeeper;
        this.uom = uom;
        this.name = name;
        this.quantity = quantity;
        this.price = price;
        this.image = image;
    }
    public Products(Shopkeeper shopkeeper, Uom uom, String name, int quantity, int price, byte[] image, Set<OrderDetails> orderDetailses, Set<Cart> carts) {
       this.shopkeeper = shopkeeper;
       this.uom = uom;
       this.name = name;
       this.quantity = quantity;
       this.price = price;
       this.image = image;
       this.orderDetailses = orderDetailses;
       this.carts = carts;
    }
   
    public Integer getPId() {
        return this.PId;
    }
    
    public void setPId(Integer PId) {
        this.PId = PId;
    }
    public Shopkeeper getShopkeeper() {
        return this.shopkeeper;
    }
    
    public void setShopkeeper(Shopkeeper shopkeeper) {
        this.shopkeeper = shopkeeper;
    }
    public Uom getUom() {
        return this.uom;
    }
    
    public void setUom(Uom uom) {
        this.uom = uom;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }
    public Set<OrderDetails> getOrderDetailses() {
        return this.orderDetailses;
    }
    
    public void setOrderDetailses(Set<OrderDetails> orderDetailses) {
        this.orderDetailses = orderDetailses;
    }
    public Set<Cart> getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set<Cart> carts) {
        this.carts = carts;
    }




}


