package entity;
// Generated 02-Mar-2021, 6:31:47 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Shopkeeper generated by hbm2java
 */
public class Shopkeeper  implements java.io.Serializable {


     private Integer SId;
     private Accounts accounts;
     private String name;
     private String shopName;
     private String address;
     private int phone;
     private String email;
     private Set<OrderDetails> orderDetailses = new HashSet<OrderDetails>(0);
     private Set<Products> productses = new HashSet<Products>(0);

    public Shopkeeper() {
    }

	
    public Shopkeeper(Accounts accounts, String name, String shopName, String address, int phone, String email) {
        this.accounts = accounts;
        this.name = name;
        this.shopName = shopName;
        this.address = address;
        this.phone = phone;
        this.email = email;
    }
    public Shopkeeper(Accounts accounts, String name, String shopName, String address, int phone, String email, Set<OrderDetails> orderDetailses, Set<Products> productses) {
       this.accounts = accounts;
       this.name = name;
       this.shopName = shopName;
       this.address = address;
       this.phone = phone;
       this.email = email;
       this.orderDetailses = orderDetailses;
       this.productses = productses;
    }
   
    public Integer getSId() {
        return this.SId;
    }
    
    public void setSId(Integer SId) {
        this.SId = SId;
    }
    public Accounts getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Accounts accounts) {
        this.accounts = accounts;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getShopName() {
        return this.shopName;
    }
    
    public void setShopName(String shopName) {
        this.shopName = shopName;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public int getPhone() {
        return this.phone;
    }
    
    public void setPhone(int phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set<OrderDetails> getOrderDetailses() {
        return this.orderDetailses;
    }
    
    public void setOrderDetailses(Set<OrderDetails> orderDetailses) {
        this.orderDetailses = orderDetailses;
    }
    public Set<Products> getProductses() {
        return this.productses;
    }
    
    public void setProductses(Set<Products> productses) {
        this.productses = productses;
    }




}


