package entity;
// Generated 02-Mar-2021, 6:31:47 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Uom generated by hbm2java
 */
public class Uom  implements java.io.Serializable {


     private int uomId;
     private String uomName;
     private Set<Products> productses = new HashSet<Products>(0);

    public Uom() {
    }

	
    public Uom(int uomId, String uomName) {
        this.uomId = uomId;
        this.uomName = uomName;
    }
    public Uom(int uomId, String uomName, Set<Products> productses) {
       this.uomId = uomId;
       this.uomName = uomName;
       this.productses = productses;
    }
   
    public int getUomId() {
        return this.uomId;
    }
    
    public void setUomId(int uomId) {
        this.uomId = uomId;
    }
    public String getUomName() {
        return this.uomName;
    }
    
    public void setUomName(String uomName) {
        this.uomName = uomName;
    }
    public Set<Products> getProductses() {
        return this.productses;
    }
    
    public void setProductses(Set<Products> productses) {
        this.productses = productses;
    }




}


